services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    hostname: Frankfurt am Main, South-East
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./smokeping/config:/config
      - ./smokeping/data:/data
      - ../logs/smokeping/apache2:/var/log/apache2
      - ./smokeping/basepage.html:/etc/smokeping/basepage.html:ro
    ports:
      - 22002:80
    restart: always
